(function(){var b=this;var f=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},k=function(a,c){return a<c?-1:a>c?1:0};var l;a:{var m=b.navigator;if(m){var n=m.userAgent;if(n){l=n;break a}}l=""};var r=-1!=l.indexOf("Opera"),t=-1!=l.indexOf("Trident")||-1!=l.indexOf("MSIE"),u=-1!=l.indexOf("Edge"),v=-1!=l.indexOf("Gecko")&&!(-1!=l.toLowerCase().indexOf("webkit")&&-1==l.indexOf("Edge"))&&!(-1!=l.indexOf("Trident")||-1!=l.indexOf("MSIE"))&&-1==l.indexOf("Edge"),w=-1!=l.toLowerCase().indexOf("webkit")&&-1==l.indexOf("Edge"),x=function(){var a=b.document;return a?a.documentMode:void 0},y;
a:{var z="",A=function(){var a=l;if(v)return/rv\:([^\);]+)(\)|;)/.exec(a);if(u)return/Edge\/([\d\.]+)/.exec(a);if(t)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(w)return/WebKit\/(\S+)/.exec(a);if(r)return/(?:Version)[ \/]?(\S+)/.exec(a)}();A&&(z=A?A[1]:"");if(t){var B=x();if(null!=B&&B>parseFloat(z)){y=String(B);break a}}y=z}
var C=y,D={},E=function(a){if(!D[a]){for(var c=0,d=f(String(C)).split("."),e=f(String(a)).split("."),g=Math.max(d.length,e.length),h=0;0==c&&h<g;h++){var W=d[h]||"",X=e[h]||"",Y=RegExp("(\\d*)(\\D*)","g"),Z=RegExp("(\\d*)(\\D*)","g");do{var p=Y.exec(W)||["","",""],q=Z.exec(X)||["","",""];if(0==p[0].length&&0==q[0].length)break;c=k(0==p[1].length?0:parseInt(p[1],10),0==q[1].length?0:parseInt(q[1],10))||k(0==p[2].length,0==q[2].length)||k(p[2],q[2])}while(0==c)}D[a]=0<=c}},F=b.document,aa=F&&t?x()||
("CSS1Compat"==F.compatMode?parseInt(C,10):5):void 0;var G;if(!(G=!v&&!t)){var H;if(H=t)H=9<=Number(aa);G=H}G||v&&E("1.9.1");t&&E("9");var I=["top","right","bottom","left"],J=function(a,c,d){a={type:a,node_id:c};void 0!==d&&(a.field_name=d);return a},L=function(a,c,d,e){var g={};g.element=a;a={type:"element"};a.spec=g;K(a,c,d,e);return a},N=function(a,c,d){return M("horizontal-list",a,c,d)},O=function(a,c,d){return M("vertical-list",a,c,d)},M=function(a,c,d,e){var g={elements:["logoMCImage","clickTFText"]};g.margin=c;c={};c.type=a;c.spec=g;K(c,d,e,void 0);return c},K=function(a,c,d,e){if(4!=d.length)throw Error("The anchors should be an array of length 4.");
c&&(a.alignments=c);for(c=0;c<I.length;++c)d[c]&&(a[I[c]]=d[c]);void 0!==e&&(a.z_index=e)};var ba={canvas:{backgroundColor:"back1MCColor"},headlineBar:{backgroundColor:"back2MCColor"},text1TFText:{font_level:1,color:"text1TFTextColor",backgroundColor:"back2MCColor"},text2TFText:{font_level:2,color:"text2TFTextColor",backgroundColor:"back1MCColor"},clickTFText:{color:"clickTFTextColor",weight:1/28,backgroundColor:"clickTFBackColor"}},P={text1TFText:{color:"text2TFTextColor",backgroundColor:"back1MCColor"},clickTFText:{displayType:"nessieButton"}},ca=J("shape","adContent"),da=J("shape","headline-background"),
ea=J("product","product-image",void 0),fa=J("logo","logo-image",void 0),Q=J("text","headline",void 0);Q.component_type="headline";var R=J("text","description",void 0);R.component_type="description";
var ga={elements:{canvas:ca,headlineBar:da,product1MCImage:ea,logoMCImage:fa,text1TFText:Q,text2TFText:R,clickTFText:J("button","button",void 0)},styles:ba,variations:{square1:{styles:{text1TFText:{padding:"10%"}},text1:L("text1TFText","top left right",["0","0","max(text1 20px, 85%)","0"]),product:L("product1MCImage","top",["text1 1px","0","40%","0"]),text2:L("text2TFText","left",["product","logoAndButton","",""]),logoAndButton:O("auto","right",["product","","","60%"])},square2:{styles:{text1TFText:{padding:"10%"}},
text1:L("text1TFText","top left right",["0","0","max(text1 25px, 75%)","0"]),product:L("product1MCImage","left",["text1 0","50%","0","0"]),text2:L("text2TFText","",["text1","","logoAndButton","product"]),logoAndButton:N("auto","",["70%","","","product"])},square3:{text1:L("text1TFText","top left right",["0","0","max(text1 25px, 75%)","0"]),product:L("product1MCImage","left",["text1 0","65%","0","0"]),text2:L("text2TFText","",["text1","20%","","product"]),logoAndButton:O("auto","right",["text1","",
"","text2"])},tower1:{styles:{text1TFText:{padding:"10%"}},text1:L("text1TFText","top left right",["0","0","70%","0"]),product:L("product1MCImage","top",["text1 1px","0","40%","0"]),text2:L("text2TFText","",["product","7%","logoAndButton","7%"]),logoAndButton:O("auto","bottom",["","","10%",""])},tower2:{styles:{text1TFText:{padding:"10%"}},text1:L("text1TFText","top left right",["0","0","70%","0"]),product:L("product1MCImage","top",["text1 1px","0","50%","0"]),text2:L("text2TFText","",["product",
"7%","logoAndButton","7%"]),logoAndButton:N("even_left","",["min(text1, 80%)","","",""])},banner1:{calibrations:["AspectRatioLE 2 0"],styles:{product1MCImage:{verticalFill:"true"},text1TFText:{padding:"10%"}},product:L("product1MCImage","left",["0","60%","0","0"]),text1:L("text1TFText","top left right",["0","0","60%","product 0"]),text2:L("text2TFText","",["text1","logoAndButton","","product"]),logoAndButton:O("auto","right",["text1","","","60%"])},banner2:{calibrations:["AspectRatioLE 5 0"],product:L("product1MCImage",
"left",["0","70%","0","0"]),text1:L("text1TFText","left",["","40%","","product 4%"]),text2:L("text2TFText","",["","logoAndButton","","text1 6%"]),logoAndButton:N("auto","right",["","","","60%"])},smallSquare1:{styles:P,product:L("product1MCImage","top",["0","0","60%","0"]),text1:L("text1TFText","left",["product","","logoAndButton",""]),text2:L("text2TFText","top left",["product","","logoAndButton",""],1),logoAndButton:O("auto","bottom",["60%","","",""])},smallSquare2:{styles:P,product:L("product1MCImage",
"top",["0","0","60%","0"]),text1:L("text1TFText","left",["product","","logoAndButton",""]),text2:L("text2TFText","top left",["product","","logoAndButton",""],1),logoAndButton:N("auto","bottom",["","10%","","10%"])},smallBanner1:{styles:P,product:L("product1MCImage","left",["0","65%","0","0"]),text1:L("text1TFText","left",["","logoAndButton","","product"]),text2:L("text2TFText","left",["","logoAndButton","","product"],1),logoAndButton:O("even_left_extra","right",["","2%","","75%"])},smallBanner2:{styles:P,
product:L("product1MCImage","left",["0","60%","0","0"]),text1:L("text1TFText","left",["","logoAndButton","","product"]),text2:L("text2TFText","left",["","logoAndButton","","product"],1),logoAndButton:N("auto","right",["","2%","","60%"])}}},S=function(a){window.renderAd(a,ga,function(){var a=document.getElementById("adContent"),d=a.getAttribute("data-variation"),a=parseInt(a.style.width,10),e=document.getElementById("headline-background"),g=document.getElementById("headline"),h=document.getElementById("product-image");
if(g)switch(d){case "smallBanner1":case "smallBanner2":case "smallSquare1":case "smallSquare2":e.style.display="none";break;case "banner2":d=h?parseInt(h.style.left,10)+parseInt(h.style.width,10):0;e.style.left=d+"px";e.style.width=parseInt(g.style.width,10)+Math.round(.08*a)+"px";e.style.height="100%";break;case "banner1":d=h?parseInt(h.style.left,10)+parseInt(h.style.width,10):0;e.style.top=g.style.top;e.style.left=d+"px";e.style.width="100%";e.style.height=g.style.height;break;case "square1":case "square2":case "square3":case "tower1":case "tower2":e.style.top=
g.style.top,e.style.left="0px",e.style.width="100%",e.style.height=g.style.height}else e.style.display="none"})},T=["onAdData"],U=b;T[0]in U||!U.execScript||U.execScript("var "+T[0]);for(var V;T.length&&(V=T.shift());)T.length||void 0===S?U=U[V]?U[V]:U[V]={}:U[V]=S;})()
